### ISSUE TITLE
(#2) Service temporarily unavailable

### ISSUE THREAD

**Issue by christianto88** [facebook/facebook-nodejs-business-sdk#103]
### Which SDK version are you using?
    "facebook-nodejs-business-sdk": "^3.2.10",

### What's the issue?
Get ad account insights from specific time_range error
### Steps/Sample code to reproduce the issue
```
    let result = await adsSdk.getInsights(fields, {
            time_range: { since: date, until: date }
          });
```

#### Observed Results:

  * What happened?  This could be a description, log output, etc.
Facebook return (#2) Service temporarily unavailable
#### Expected Results:

  * What did you expect to happen?
Get insights data from that ad account on that particular time range

**Comment by michaelwclark** [comment]
This isn't an SDK code issue, but rather a Facebook Services issue. I'd recomend surfacing these issues in the new [Developer Community Forum](https://developers.facebook.com/community) or [Platform Bugs](https://developers.facebook.com/support/bugs/).

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
