### ISSUE TITLE
TypeError: Cannot read property '_startOffset' of undefined

### ISSUE THREAD

**Issue by briank621** [facebook/facebook-nodejs-business-sdk#107]
### Which SDK version are you using?
3.3
### What's the issue?
Cannot upload a video through the SDK
### Steps/Sample code to reproduce the issue
```
const adsSdk = require('facebook-nodejs-business-sdk');
const accessToken = 'mytoken';
const api = adsSdk.FacebookAdsApi.init(accessToken);

api.setDebug(true)
let AdVideo = adsSdk.AdVideo
let advideo = new AdVideo(null, {[AdVideo.Fields.filepath]: "sample.mp4"}, "act_<myadaccount>")
advideo.create().then(res=>{
	console.log(res)
})
```
#### Observed Results:
The SDK returns an error of `Cannot read property '_startOffset' of undefined`

#### Expected Results:
The video to be created.

#### Notes:

This bug is already mentioned in [this issue](https://github.com/facebook/facebook-nodejs-business-sdk/issues/54). The problem seems to be with Gulp but the fix hasn't been updated, and the old issue has been prematurely closed.

**Comment by jingping2015** [comment]
Hi, Looks like this issue is caused by `gulp`, an work around solution would be in `cjs.js` line 9131, change to 
```
var _this8 = _this7;
```

**Comment by bazanga** [comment]
Yes, I've been using the workaround, but I'm wondering if there was a plan to fix it in production so I don't have to work off of a fork. 

What specifically is the issue in Gulp? I can try and take a stab at it.

**Comment by mvhirsch** [comment]
@jingping2015 I'm running into this, too (SDK `v4.0.3`).
Are there any plans to get this fixed soon?
