### ISSUE TITLE
Typo in src/api-batch.js

### ISSUE THREAD

**Issue by lotsoftick** [facebook/facebook-nodejs-business-sdk#113]
Looks like you have a typo in src/api-batch.js, on the line 118. 
i think instead of ``nam: name``, it should be ``name: name``

<img width="519" alt="bug" src="https://user-images.githubusercontent.com/24815689/60297616-a6139e80-9939-11e9-9c4c-37f06dd4b6b4.png">

And also can you please help me to figure out how to create Async Batch Request https://developers.facebook.com/docs/graph-api/asynchronous-batch-requests/

here is my batch request creation code, but i can't create async batch requests.
```
const adsSdk = require('facebook-nodejs-business-sdk');
const batchApi = adsSdk.FacebookAdsApiBatch;
const api = adsSdk.FacebookAdsApi.init(token);
const batchReq = new batchApi(api);

batchReq.add(method, rel_url, params, [], d => (), e => ());
batchReq.execute();
```
Thanks.

**Comment by jingping2015** [comment]
Thanks for reporting this issue, it already be fixed in latest release.
