### ISSUE TITLE
NPM package wasn't updated to version 4.0

### ISSUE THREAD

**Issue by iamkhan21** [facebook/facebook-nodejs-business-sdk#118]
The latest version of Npm package is 3.3, but I receive next error - (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v4.0.

**Comment by jingping2015** [comment]
Hi, Thanks for report the issue. v4.0.1 should be on https://www.npmjs.com/package/facebook-nodejs-business-sdk.
