### ISSUE TITLE
TypeError: Cannot read property '_startOffset' of undefined

### ISSUE THREAD

**Issue by mvhirsch** [facebook/facebook-nodejs-business-sdk#120]
### Which SDK version are you using?

4.0.4

### What's the issue?

It's basically the same issue as in #107 and #54 but it's not resolved since months.

Yes I know there is a workaround, but it's not a good advice at all to manipulate files under `node_modules/` directory. While this _does_ fix my problem (the code looking for is on line 9693), I'm not able to commit these changes in my repository, nor I'm able to run my build pipeline and deploying this change.

Is there no way on fixing this in a more stabilized and practical way?

### Steps/Sample code to reproduce the issue

```
const advideo = new AdVideo(null, null, 'act_' + account_id);
advideo.set('filepath', path);
advideo.set('name', title);

await advideo.create(); // will throw exception
```

#### Observed Results:

  * The above code will result in `Cannot read property '_startOffset' of undefined`.

#### Expected Results:

  * Uploading video in chunks, without error.

**Comment by iqueryable** [comment]
This is still not working in version `4.0.6`.

I understand the problem has been identified and can be fixed according to https://github.com/facebook/facebook-nodejs-business-sdk/issues/54#issuecomment-400479641, but when can we expect that to happen?

**Comment by mvhirsch** [comment]
I'll give it another shot with v5.

**Comment by nicolasabric** [comment]
@mvhirsch Did you managed to make it work without modifying cjs.js? BTW I still have the issue with version 6.

**Comment by mvhirsch** [comment]
> Did you managed to make it work without modifying cjs.js?

Unfortunately not.
