### ISSUE TITLE
Can't create Ad Account for Child Business Manager

### ISSUE THREAD

**Issue by matkoson** [facebook/facebook-nodejs-business-sdk#122]
### Which SDK version are you using?
^4.0.5
### What's the issue?

I am trying to implement Business Onboarding flow. I manage to get an access token through Facebook Login, then I create Child Business Manager(for a test user created in Facebook App) and I fetch Admin System User's access token(from the Child). The issue is that while I am trying to create Ad Account for the newly created Child Business Manger, I always get the same error response `"(#100) The parameter name is required"`. 

Well, the `name` parameter is certainly attached into the config object on `new Business(child_business_id)).createAdAccount`

### Steps/Sample code to reproduce the issue
1. Create a test user in your Facebook App, set `ads_management` and `business_management` permissions on this test user, then assign some password for the user.
2. Create 'Log in with Facebook' button, and generate access token by signing in with Test User's credentials
3. Using the given Test User access token, create Child Business Manager with `owned_businesses`
edge, on your Parent Business Manger node, which will return created Child BM's id
4. Using this id as a node, call the `access_token` edge, which will return Admin System User's access token for you
5. Try to create Ad Account for the newly created Child BM, using `Business` object from nodejs SDK
```
app.post('/createAdAccount', async (req, res) => {

    const { child_business_id, token } = req.query;

        const params = {
            'name': 'Advertisers Ad Account',
            'currency': 'USD',
            'timezone_id': '1',
            'end_advertiser': 'NONE',
            'media_agency': 'NONE',
            'partner': 'NONE',
            "access_token": token
        };
        const account = await (new Business(child_business_id)).createAdAccount(
            {
                params
            }
        ).then(res => { debugger; }).catch(err=> {debugger;});


    const  account_id = account.id;



});

```

#### Observed Results:

  * What happened?  This could be a description, log output, etc.

The output is always `"(#100) The parameter name is required"`. Another thing is that when I try to create the new Ad Account using `adaccount` edge on Graph API, I get the following error
`"(#275) Cannot determine the target object for this request. Currently supported objects include ad account, business account and associated objects."`

![image](https://user-images.githubusercontent.com/41837132/65304123-64c51080-db6f-11e9-84a8-012af6a39549.png)

#### Expected Results:

  * What did you expect to happen?

- I expected to receive an Ad Account Id, as is stated in the guide linked below
https://developers.facebook.com/docs/business-sdk/common-scenarios/onboard-at-scale/common-scenarios

**Comment by martinploug** [comment]
Hi Matko,

Do you have the Ads Management Standard Access ? We had some issues with creating an Ad Account without it.

But now we found another problem, when we try to create a Child Business Manager for a user who is not a test-user of the app we get this error "message":"It doesn't look like you have permission to create a new Business Manager."

Do you have to same problem ?

**Comment by matkoson** [comment]
As there were no answer, like anywhere, not only here, additionally I no longer have access to the codebase to which the issue pertain, so I suppose the only thing left for me to do here is to close it.

**Comment by abhishekq61** [comment]
I am facing similar issue. Getting error - "(#275) Cannot determine the target object for this request. Currently supported objects include ad account, business account and associated objects." while making post request to -''<business-id>/adaccount"
Can you please help how did you resolved this issue
