### ISSUE TITLE
Instagram API

### ISSUE THREAD

**Issue by bwyyoung** [facebook/facebook-nodejs-business-sdk#124]
Could you share an example of how I may use this SDK to obtain information on an instagram business user?

https://developers.facebook.com/docs/instagram-api/reference/user

Is it possible to get the user's list of followers, and list of following?

**Comment by jingping2015** [comment]
You should use `IGUser` to obtain instagram business user. 
https://github.com/facebook/facebook-nodejs-business-sdk/blob/945d03c78b08549993c2a9dcce20fdfa976ca812/src/objects/ig-user.js#L20
