### ISSUE TITLE
Need TypeScript definitions

### ISSUE THREAD

**Issue by kevinclarkadstech** [facebook/facebook-nodejs-business-sdk#130]
### Which SDK version are you using?  

"^5.0.1"

### What's the issue?  

Need TypeScript definitions.

### Steps/Sample code to reproduce the issue
1) Create a .ts file
2) Type import fbSdk from 'facebook-nodejs-business-sdk';

#### Observed Results:

  * What happened?  This could be a description, log output, etc.

```
IDE throws an error: Could not find a declaration file for module 'facebook-nodejs-business-sdk'. '/Dev/facebook-nodejs-business-sdk-test/node_modules/facebook-nodejs-business-sdk/dist/cjs.js' implicitly has an 'any' type.
  Try `npm install @types/facebook-nodejs-business-sdk` if it exists or add a new declaration (.d.ts) file containing `declare module 'facebook-nodejs-business-sdk';`ts(7016)
```

#### Expected Results:

  * What did you expect to happen?

 To get TypeScript definitions, as this is 2019 and this is an enterprise SDK library.  It makes it much easier to consume a library without runtime errors and without consulting documentation frequently.

**Comment by jookovjook** [comment]
@kevinclarkadstech Types can be generated with [dts-gen](https://github.com/Microsoft/dts-gen) using it **locally**:

```
yarn add dts-gen
./node_modules/.bin/dts-gen -m facebook-nodejs-business-sdk -d types
```

Than add generated types to `tsconfig.json`:
```
"compilerOptions": {
  ...
  "typeRoots": [
    ...
    "./types"
...
```
Hope it will help : )

**Comment by Xeoncross** [comment]
Would love to see TypeScript definitions maintained as well.

**Comment by bduffany** [comment]
The dts-gen solution mentioned by @jookovjook didn't work for me.

**Comment by kevinclarkadstech** [comment]
> @kevinclarkadstech Types can be generated with [dts-gen](https://github.com/Microsoft/dts-gen) using it **locally**:
> 
> 
> 
> ```
> 
> yarn add dts-gen
> 
> ./node_modules/.bin/dts-gen -m facebook-nodejs-business-sdk -d types
> 
> ```
> 
> `/types/facebook-nodejs-business-sdk` should be generated under the project root
> 
> 
> 
> Than add generated types to `tsconfig.json`:
> 
> <pre>
> 
> {
> 
>   "compilerOptions": {
> 
>     ...
> 
>     "typeRoots": [
> 
>       ...
> 
>       <b>"node_modules/@types",</b>
> 
>       <b>"./types"</b>
> 
>       ]
> 
>   },
> 
>   "exclude": [<b>"node_modules"</b>]
> 
> }
> 
> </pre>
> 
> Hope it will help : )

Thanks for responding...I just looked at the dts-gen library and noticed this:


This trade-off comes with a price -- you'll see a lot of anys in function parameters and return types. You may also see properties that are not intended for public use. dts-gen is meant to be a starting point for writing a high-quality definition file.

It would be better if Facebook devs would stop trying to create their own sht like Flow and just embrace TypeScript. I have heard from one popular Facebook developer that he never tried TypeScript. Just baffling.

**Comment by jookovjook** [comment]
@kevinclarkadstech Yeah. You'll see lots of warnings using this solution - it's not the best : ) Be prepared to use lot of `@ts-ignore`. But I think it's possible to make a fork of `dts-gen` which will work well with fb

**Comment by simllll** [comment]
It's been quite a while since this issue has been created, is there anything new regarding TS support?

**Comment by kevinclarkadstech** [comment]
> It's been quite a while since this issue has been created, is there anything new regarding TS support?

There won't be...Facebook developers have not even tried TS, they just use Flow. 👎 I mean this issue has been open for over 1/2 a year. Thank God I moved to a different project and don't need to use this library anymore. :wipes brow

**Comment by simllll** [comment]
@kevinclarkadstech what project do you use now? Is there any library which has ts support for the fb business sdk? I started to define some of the methods by using the dts-generated files as a basis, if we work together we could try to set something up in the https://github.com/DefinitelyTyped/DefinitelyTyped project.

**Comment by noudadrichem** [comment]
To what project did you move? Another FB SDK? @kevinclarkadstech

**Comment by kevinclarkadstech** [comment]
> To what project did you move? Another FB SDK? @kevinclarkadstech 

I actually moved to a new project on a new job :) So I did not need the SDK anymore.

**Comment by kevinclarkadstech** [comment]
> @kevinclarkadstech what project do you use now? Is there any library which has ts support for the fb business sdk? I started to define some of the methods by using the dts-generated files as a basis, if we work together we could try to set something up in the https://github.com/DefinitelyTyped/DefinitelyTyped project.

Sorry, just seeing this now! Have you been using this SDK still?

I do think community supported type definitions would be better than none, but it’s pretty frustrating how against TS Facebook are. They keep using Flow. They always want to make everything for their little eco system (Yarn, Jest, Flow etc). Dan Abramov said he had never even tried TypeScript! Amusing to me because he also founded Redux, which is HORRIBLE without help from TS. 😅

Community supported type definitions usually work if a) the library is small or b) the library is big, but there are a lot of devs that use it and are willing to contribute. Otherwise it’s easy for them to get out of date.

Since you have looked at it more thoroughly, how hard does it seem to create full definitions?

**Comment by jlubeck** [comment]
While waiting on official definitions, I went ahead and created my own with `dts-gen` and I've been working nicely with it.

I ran into a problem though. I want to work with pagination now, and looking at the docs it mentions a Cursor object, which is in `src/cursor.js`. For some reason, this file was not exported by `dts-gen`

Anyone knows how I can work with it so I can use pagination in my calls with Typescript?

Thanks!

**Comment by jlubeck** [comment]
@simllll did you have to use Pagination yourself? Hopefully you are still using this library

**Comment by Desnoo** [comment]
@jlubeck I have a little example of how to use the cursor.

This will `const cursor = igUser.getMedia(fields..., options, false)` return a cursor. If you set the last argument to false it will return a cursor.
Then you can call `cursor.hasNext()` to check if there is data for this API call.
If there is data for this cursor you can get the data by calling `cursor.next()`. This will return a Promise.

I hope that helps.

**Comment by jlubeck** [comment]
hey @Desnoo thank you for your reply.

When creating my own definition, I changed the one I want from this:

```
getLeads(fields: any, ...args: any[]): any;
```
to this

```
getLeads(fields: any, ...args: any[]): Lead[];
```

That gave me all the code completion . 

But with that, if I try: 
```
let cursor = await ad.getLeads([],{},false);
```

I then get an error `Property 'hasNext' does not exist on type 'Lead[]'`

If I change the definition back to any, the hasNext doesn't error out, but how to I get the code completion back?

**Comment by Desnoo** [comment]
@jlubeck `getLeads(fields: any, ...args: any[]): Lead[];`
Well you defined the return type as `Lead[]` and not of the type `Cursor`.

The Type Cursor should look something like:

`type Cursor<T> {
  hasNext(): boolean;
  next(): Promise<T>;
}`

This will be the return type if you pass `false` as the last argument to the `getLeads(): Cursor<Lead[]>` method.
If you pass true or leave the last argument empty, then your definition should nearly work. The return type of `getLeads` then should be `Promise<Lead[]>`. I'm not completely sure, but it should look like this.

**Comment by jlubeck** [comment]
Thank you so Much @Desnoo with your help now I implemented the methods like this:

```typescript
export type Cursor<T> = Array<T> & {
    hasNext(): boolean;
    next(): Promise<Cursor<T>>;
}

getLeads(fields: any, options: any, ignoreCursor: boolean): Promise<Cursor<Lead>>;

getLeads(fields: any, ...args: any[]): Promise<Lead[]>;
```

and works like charm!

**Comment by abhijithvijayan** [comment]
https://stackoverflow.com/a/29463433

**Comment by abhijithvijayan** [comment]
Setting the `"typeRoots"` property doesn't work. But setting `"path"` does.

Solution https://github.com/microsoft/TypeScript/issues/22217#issuecomment-369783776

**Comment by thekip** [comment]
@jlubeck could you share your forked dts-gen and typings with all latest changes? Maybe we can then push it to DefinetelyTyped

**Comment by jlubeck** [comment]
@thekip I only update a couple that were what I was using... definitely not ready to push to a repo or something unfortunately

**Comment by kevinclarkadstech** [comment]
Just popped in to say sorry you guys are dealing with this still. I was actually looking at Facebooks NLP Node.js SDK today and OF COURSE....no TypeScript. So I went on to alternatives like Azure's LUIS. 😑🙄

**Comment by kevinclarkadstech** [comment]
Facebook seem to refuse to embrace TypeScript across the board. Don't hold your breath. Shit, they haven't even responded to this issue. 😡

**Comment by nmggithub** [comment]
I know people hate self-promo, and I don't know if this will work for most of you, but I've made a strongly-typed Facebook Graph API client (the nodes are typed as well). I have not tested it with ad-related endpoints, but it does work well for the Messenger Platform in my tests. Here is the link: https://github.com/nmggithub/fbsdk-ts

**Comment by mptorz** [comment]
Bumping up the issue

**Comment by dcgudeman** [comment]
Similar issue. Would love it if facebook would officially address it.

**Comment by yonihod** [comment]
I wonder if there is a good solution for this today?

**Comment by noudadrichem** [comment]
Probably not as FB is all in the 'flow' party.

**Comment by kevinclarkadstech** [comment]
I probably should just abandon this issue, it has been open 1.5 years with no response from anyone from facebook.

**Comment by Arootin** [comment]
Bumping up the issue

**Comment by william-takayama** [comment]
loading . . .

**Comment by AlonMiz** [comment]
> loading . . .

connection timeout ⚠️

**Comment by ugglr** [comment]
Even if FB does not like typescript they should cater to their customers who actually use their advertising services. Now more than ever since apple basically has rendered "easy" use of their tracking obsolete. Not catering to typescript customers is the same as not supporting developers who are using Python or whatever. 

If a company don't serve the costumers who are **paying** for their service then that's a company who will never have long term success.

**Comment by bogdibota** [comment]
> That seems like an issue with dts-gen and not this package.

seems to be related to this PR: https://github.com/microsoft/dts-gen/pull/174

**Comment by yesh-cash** [comment]
I was very disappointed to stumble upon this thread.
I would go as far as to say this is a must in 2022.

**Comment by dima-gusyatiner** [comment]
I was very disappointed to stumble upon this thread.
I would go as far as to say this is a must in 2022.

**Comment by achie27** [comment]
Consider this bumped

**Comment by only4lee** [comment]
I'd honestly settle if FB actually created swagger/OAS definitions. I do see one in FB's "incubating" github project that captures their conversions api, but it's unmaintained (at version 8 of the api).  Using this I generated my own typescript library using the Open API code generator (after modifying it to align to the current version (v12).

Works great -- only issue that it is problematic that FB chooses not to publish their APIs this way.

**Comment by kigorw** [comment]
Bump! It's time to release types.

**Comment by nmggithub** [comment]
Facebook seems to really like their own type system, Flow. They probably will never release types.

**Comment by jRexhmati** [comment]
Crazy!!! Still no support for types, such a shame :/

**Comment by K-Mistele** [comment]
Ridiculous that they don't support this.

**Comment by alexgrigorehww** [comment]
I find it impossible to use this library because only some random features are documented and absolutely no autocomplete. I'll just go with rest api!

**Comment by kevinclarkadstech** [comment]
Just keep creating new issues instead of only responding to this.  Flood their issues with Need TypeScript Types.

**Comment by kevinclarkadstech** [comment]
LOL from their README

"The Facebook [Business SDK](https://developers.facebook.com/docs/business-sdk) is a one-stop shop to help our partners better serve their businesses. Partners are using multiple Facebook API's to serve the needs of their clients. Adopting all these API's and keeping them up to date across the various platforms can be time consuming and ultimately prohibitive."

Yes, adopting these APIs without TypeScript types is TIME CONSUMING and PROHIBITIVE.

**Comment by nusendra** [comment]
bump

**Comment by brent-weatherall** [comment]
Another bump for the party. How is this still not supported? :(

**Comment by KloudCoder** [comment]
I'm shocked. No comment for Facebook. NoTypings for such a big project

**Comment by gustavogr** [comment]
Bump. Just stumbled with this when a client asked to be integrated with Facebook Business.

**Comment by kigorw** [comment]
bump to keep it active

**Comment by lluchkaa** [comment]
another bump

**Comment by Vict0rd** [comment]
BUUUMP

**Comment by dtpietrzak** [comment]
BUUMMPPPP

**Comment by kevinclarkadstech** [comment]
Stop thumb downing bumps @Desnoo . Facebook deserves the thumbs down.

**Comment by Desnoo** [comment]
@kevinclarkadstech we also do need this. But if you wait for a response you only get notifications about the bump messages and this is really annoying. Every week is ok but not every day.

**Comment by Vict0rd** [comment]
PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62989

**Comment by Vict0rd** [comment]
The PR is merged.

**Comment by kevinclarkadstech** [comment]
I guess I'm closing this so I don't have to see it anymore. Annoying how the community has to write definitions for a product that Facebook profits from.

**Comment by phillipmohr** [comment]
Could someone please explain how to use the type definitions from DefinitelyTyped?

Example: 
```js
const leadgenForms: LeadgenForm[] = await (new Page(pageId)).getLeadGenForms([
    LeadgenForm.Fields.questions,
])
```

Getting `Type 'Cursor' is not assignable to type 'LeadgenForm[]'.`, which makes sense since getLeadGenForms returns `Promise<Cursor>`. I also tried 

```js
const leadgenForms: Cursor<LeadgenForm[]> = await (new Page(pageId)).getLeadGenForms([
    LeadgenForm.Fields.questions,
]);
```

Not sure how it's supposed to work... Any help is appreciated

**Comment by Vict0rd** [comment]
@phillipmohr I use this method
```typescript
  public async *fetchInsightPages({
    fields,
    params,
  }: {
    fields: string[];
    params: Record<string, string>;
  }): AsyncGenerator<Insight[]> {
    const cursor = await this.fbAdAccount.getInsights(fields, params);

    while (true) {
      yield cursor.map((item): Insight => {
        return {
          adId: item.ad_id,
          adName: item.ad_name,
          ...
          startDate: item.date_start,
          endDate: item.date_stop,
        };
      });

      if (cursor.hasNext()) {
        await cursor.next();
      } else {
        break;
      }
    }
  }
```

Maybe next method will work too
```typescript
  public async *fetchInsights({
    fields,
    params,
  }: {
    fields: string[];
    params: Record<string, string>;
  }): AsyncGenerator<Insight> {
    const cursor = await this.fbAdAccount.getInsights(fields, params);

    while (true) {
      for (const item of cursor) {
        yield {
          adId: item.ad_id,
          adName: item.ad_name,
          adSetId: item.adset_id,
          // ...
          startDate: item.date_start,
          endDate: item.date_stop,
        };
      }

      if (cursor.hasNext()) {
        await cursor.next();
      } else {
        break;
      }
    }
  }
```

**Comment by kevjin** [comment]
I made definitelytyped's ts definitions work with this package, by doing the following:
```
import TypedBusinessSDK from 'facebook-nodejs-business-sdk';
const BusinessSDK: typeof TypedBusinessSDK = require('facebook-nodejs-business-sdk');
```

not ideal for imports but at least stuff is typed now
