### ISSUE TITLE
Get campaign by Id?

### ISSUE THREAD

**Issue by actuallymentor** [facebook/facebook-nodejs-business-sdk#131]
I'm trying to get the current status of my campaign. The SDK has `account.getCampaigns()`, but that does not take an `{ id: '' }`.

How to I get the status of a *single campaign*?

Something like:

```js
const getCampaign = id => account.getCampaign( [ // <-- this function does NOT exist
	Campaign.Fields.budget_remaining,
	Campaign.Fields.lifetime_budget,
	Campaign.Fields.start_time,
	Campaign.Fields.stop_time,
	Campaign.Fields.effective_status
], { id: id } )
.then( campaign => console.log( campaign.start_time ) )
```

**Comment by mvhirsch** [comment]
Hi, it's as simple as this: https://github.com/facebook/facebook-nodejs-business-sdk#read-objects

```
const getCampaign = id => new Campaign(id)
    .read([
	Campaign.Fields.budget_remaining,
	Campaign.Fields.lifetime_budget,
	Campaign.Fields.start_time,
	Campaign.Fields.stop_time,
	Campaign.Fields.effective_status
])
.then( campaign => console.log( campaign.start_time ) )
```

Hope this works.
Greets from Austria

**Comment by jingping2015** [comment]
@mvhirsch provided a good example. So I am going to close this issue.

**Comment by actuallymentor** [comment]
Thank you for the example, this is not very clear from the `README.md`. Would you welcome a PR with a more detailed readme?
