### ISSUE TITLE
An unknown error has occurred creating Ad

### ISSUE THREAD

**Issue by danny-waite** [facebook/facebook-nodejs-business-sdk#148]
### Which SDK version are you using?
6.0.1

### What's the issue?
Getting an error when trying to create an Ad
```
{"error":{"message":"An unknown error has occurred.","type":"OAuthException","code":1,"fbtrace_id":"abc"}}
```

### Steps/Sample code to reproduce the issue
Creating the Campaign, AdSet, Ad Creative all work, the final step of creating the Ad does not.

```
campaign:
{"name":"Simple Ad Campaign","objective":"PAGE_LIKES","status":"PAUSED","special_ad_category":"NONE"}

ad set
{"name":"test","campaign_id":"12c","promoted_object":{"page_id":"456"},"status":"PAUSED","targeting":{"geo_locations":{"countries":["US"]}},"daily_budget":"1000","billing_event":"IMPRESSIONS","bid_amount":"2","optimization_goal":"REACH","data":"PAUSED"}

ad creative
{"name":"test creative","object_story_id":"123_456","status":"PAUSED"}

ad
{"name":"test ad","adset_id":"123","creative":{"creative_id":"456"},"status":"PAUSED"}
```

The page is live but I haven't gone through the verification process since the app is for internal purposes, but I'm wondering if this is the issue? The error is not very helpful obviously.

**Comment by giovotinh07111996** [comment]
me too, tha same, any news ?
