### ISSUE TITLE
Wrong case of properties in ads-insight object

### ISSUE THREAD

**Issue by perengb** [facebook/facebook-nodejs-business-sdk#15]
Got this error when calling the API using properties from the ads-insight object:

"(#100) breakdowns[0] must be one of the following values: age, country, dma, gender, frequency_value, hourly_stats_aggregated_by_advertiser_time_zone, hourly_stats_aggregated_by_audience_time_zone, impression_device, place_page_id, publisher_platform, platform_position, device_platform, product_id, region"

The HTTP call sent has the breakdowns in uppercase like this: 
breakdowns: PUBLISHER_PLATFORM,IMPRESSION_DEVICE

Made a pull request to fix:
https://github.com/facebook/facebook-nodejs-ads-sdk/pull/14

**Comment by perengb** [comment]
Is there something more that i need to do in order to merge this PR?

**Comment by vicdus** [comment]
PR already accepted. Thanks!
