### ISSUE TITLE
How to create ad image via node SDK? 

### ISSUE THREAD

**Issue by ngloom** [facebook/facebook-nodejs-business-sdk#159]
### Which SDK version are you using?
nodejs V6

### What's the issue?
There is only python & php versions  for ad image creating found here <https://developers.facebook.com/docs/marketing-api/reference/ad-image>, 
translate the code to nodejs but not working , need help to get a demo with nodejs version

**Comment by ngloom** [comment]
Find a solution finally after many failures, 
upload ad image successfully via facebook nodejs business sdk v7,
hope to help others..

```javascript
let accID = 'act_xxxxxxxx';
// file path
let filepath = '.......';
// read file conent and convert to base64 encode
let content = fs.readFileSync(filepath).toString('base64')
const adimage = await (new AdAccount(actId).createAdImage([], {
    bytes: content
}));
```

**Comment by Assain2** [comment]
Thanks for the solution! I wish this was present in the official documentation.
