### ISSUE TITLE
TOS not Accepted while creating AdSet

### ISSUE THREAD

**Issue by sGambolati** [facebook/facebook-nodejs-business-sdk#162]
### Which SDK version are you using?
v7.0.0

### What's the issue?
Can't create AdSet when Campaign's objective is `LEAD_GENERATION`.

### Steps/Sample code to reproduce the issue

``` JS
    const AdSet = bizSdk.AdSet;
    const fields = [ AdSet.Fields.Id ];

    let params = {
        "attribution_spec": [
          {
            "event_type": "CLICK_THROUGH",
            "window_days": 1
          }
        ],
        "billing_event": "IMPRESSIONS",
        "budget_remaining": "0",
        "campaign": {
          "id": "<CAMPAIGN_ID>"
        },
        "campaign_id": "<PAGE_ID>",
        "configured_status": "ACTIVE",
        "destination_type": "UNDEFINED",
        "effective_status": "CAMPAIGN_PAUSED",
        "is_dynamic_creative": false,
        "lifetime_imps": 0,
        "name": "Lead AdSet",
        "optimization_goal": "LEAD_GENERATION",
        "optimization_sub_event": "NONE",
        "promoted_object": {
          "page_id": "<CAMPAIGN_ID>"
        },
        "recurring_budget_semantics": false,
        "status": "ACTIVE",
        "targeting": {
          "age_max": 65,
          "age_min": 18,
          "geo_locations": {
            "countries": [
              "AR"
            ],
            "location_types": [
              "home",
              "recent"
            ]
          },
          "targeting_optimization": "none",
          "brand_safety_content_filter_levels": [
            "FACEBOOK_STANDARD"
          ]
        },
        "use_new_app_click": false
      }

    account.createAdSet(fields, params);
```

#### Observed Results:

**Error:** `Terms of Service Not Accepted: You can't run lead ads until your 
Facebook Page accepts Facebook's Lead Generation Terms of Service.`

I've checked that I had accepted TOS for all my pages [here](https://www.facebook.com/ads/leadgen/tos).

#### Expected Results:

AdSet successfully created. In worse case, I think Ad creation should fail, given that AdSet doesn't have a relation with Lead Gen Form.

**Comment by michaelthieulin** [comment]
Hello, same problem here and even worst.
I manage to make it worked and the problem reappear.

**Comment by gmacdev** [comment]
Did anyone find a fix? It's been days after accepting the TOS but still can't create the AdSet.

**Comment by AleAmex** [comment]
I've the same problem, TOS accepted for the page but still getting "You can't run lead ads until your Facebook Page accepts Facebook's Lead Generation Terms of Service."
