### ISSUE TITLE
Publishing v8.0?

### ISSUE THREAD

**Issue by wjarvis-verb** [facebook/facebook-nodejs-business-sdk#169]
### Which SDK version are you using?
Previously v7.0.3, I built v8.0 locally

### What's the issue?
Making a request to 
`https://graph.facebook.com/v7.0/{PIXEL_ID}/events?access_token={ACCESS_TOKEN}`

responded with a 400 error stating that this version of the API had been deprecated.  

### Steps/Sample code to reproduce the issue
From the docs,
```
'use strict';
const bizSdk = require('facebook-nodejs-business-sdk');
const ServerEvent = bizSdk.ServerEvent;
const EventRequest = bizSdk.EventRequest;
const UserData = bizSdk.UserData;
const CustomData = bizSdk.CustomData;
const Content = bizSdk.Content;

const access_token = '<ACCESS_TOKEN>';
const pixel_id = '<ADS_PIXEL_ID>';
const api = bizSdk.FacebookAdsApi.init(access_token);

let current_timestamp = Math.floor(new Date() / 1000);

const userData = (new UserData())
                .setEmail('joe@eg.com')
                .setFbp('fb.1.1558571054389.1098115397')
                .setFbc('fb.1.1554763741205.AbCdEfGhIjKlMnOpQrStUvWxYz1234567890');

const customData = (new CustomData())
                .setCurrency('usd')
                .setValue(123.45);

const serverEvent = (new ServerEvent())
                .setEventName('Purchase')
                .setEventTime(current_timestamp)
                .setUserData(userData)
                .setCustomData(customData);

const eventsData = [serverEvent];
const eventRequest = (new EventRequest(access_token, pixel_id))
                .setEvents(eventsData);


eventRequest.execute();
```

#### Observed Results:

On setting api.debug(true), I saw that the eventRequest responded with a 400 error detailing that the v7.0 API was deprecated.

As a workaround while we integrate the server side events api locally, I downloaded the v8.0 tarball and built and installed locally--it looks like the most recent version published to NPM is still 7.0.3 (https://www.npmjs.com/package/facebook-nodejs-business-sdk).  I tried adding `@8.0` to get the most recent and verified that npm told me this was not found.

#### Expected Results:

Ideally the deprecated API would work until this is published.  Do you have a timeframe for publishing?  It would be much simpler to `npm install` when deploying to production than endeavor to build this locally in our prod environment.

**Comment by jingping2015** [comment]
Thanks for repost this issue, we just have a new version release.

**Comment by wjarvis-verb** [comment]
@jingping2015 thanks!
