### ISSUE TITLE
How can I create a Campaign, AdSet and Ad in one call?

### ISSUE THREAD

**Issue by roundrobin** [facebook/facebook-nodejs-business-sdk#18]
Is there a way to do that? Or do I have to created them one by one?

**Comment by mishrakrishnakant** [comment]
Wouldn't you just chain them up in a Promise chain?

**Comment by josescasanova** [comment]
You can use the `FacebookAdsApiBatch` API (https://github.com/facebook/facebook-nodejs-ads-sdk/blob/master/src/api-batch.js#L17)

FB docs: https://developers.facebook.com/docs/marketing-api/asyncrequests/v2.11 (See `Batch Requests` midway through)

You can probably do something like:
```
const batch = new FacebookAdsApiBatch(facebookApi);

batch.add(
  'GET',
  'path/to/request/campaign',
  campaignSettings,
);

batch.add(
  'GET',
  'path/to/request/adset',
  adsetSettings,
);

batch.add(
  'GET',
  'path/to/request/ad',
  adSettings,
);

const response = await batch.execute();
```

**Comment by roundrobin** [comment]
@josescasanova How does the adset/ad knows it belongs to the campaign added earlier to the batch request?

**Comment by WilliSchmidt** [comment]
> @josescasanova How does the adset/ad knows it belongs to the campaign added earlier to the batch request?

https://developers.facebook.com/docs/graph-api/making-multiple-requests/#multiple_methods

Specifying dependencies between operations in the request:

{result=(parent operation name):(JSONPath expression)}
