### ISSUE TITLE
ISSUE: You are calling a deprecated version of the Ads API . Please update to the latest version: v10.0.

### ISSUE THREAD

**Issue by tlhfckoctbcr** [facebook/facebook-nodejs-business-sdk#187]
### Which SDK version are you using?
The latest as of nine days ago, v9.0.2.

### What's the issue?
When making a call to the API via the SDK:
```
You are calling a deprecated version of the Ads API . Please update to the latest version: v10.0.
```
### Steps/Sample code to reproduce the issue
Instantiate the SDK, make any call. I made one to GET `allCampaigns`.

#### Observed Results:

  * What happened?  This could be a description, log output, etc.

```
 (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v10.0."}
```

#### Expected Results:

  * What did you expect to happen?

I expect it to successfully make the call utilizing the most up-to-date version of the API, or at least allow for v9 usage if it is only deprecated and not entirely removed. I would imagine an update to the SDK would coincide with an update to the API.

**Comment by davidtai** [comment]
Please fix this as all of our integrations are breaking.

**Comment by lait1989** [comment]
I have the same problem. Please fix it!

**Comment by kevinmiguet** [comment]
Same problem here. Pleaaaase fix it

**Comment by sanctaignis** [comment]
Same problem! Please fix ASAP!

**Comment by sanctaignis** [comment]
Forked this repo to https://github.com/sanctaignis/facebook-nodejs-business-sdk and changed api version to v10.0. Also published to https://www.npmjs.com/package/facebook-nodejs-business-sdk-v10. Solved my problem. Can be used as temp fix.

**Comment by jingping2015** [comment]
Yea, we just release v10, please use v10 to call API v10.
