### ISSUE TITLE
Cannot send event with contents set with setContents

### ISSUE THREAD

**Issue by kevinmiguet** [facebook/facebook-nodejs-business-sdk#189]
### Which SDK version are you using?
10

### What's the issue?
when I set contents and then send the request, I get an error

the contents I use looks like this : [{"id":"H02KIDF200","quantity":1,"item_price":15.9}] 
### Steps/Sample code to reproduce the issue

send an event with custom data :
      new CustomData()
        .setCurrency("EUR")
        .setContents([{"id":"H02KIDF200","quantity":1,"item_price":15.9}])

#### Observed Results:

  * What happened?  This could be a description, log output, etc.
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'call' of undefined     at CustomData.normalize

#### Expected Results:

  * What did you expect to happen?
 
my request to be sent

**Comment by marksliva** [comment]
The contents field on `CustomData` should be an array of `Content` objects instead of plain objects:
```
    const content = (new Content())
      .setId('H02KIDF200')
      .setQuantity(1);

    const customData = (new CustomData())
      .setContents([content])
      .setCurrency('eur')
      .setValue(15.9);
```

**Comment by kevinmiguet** [comment]
Thanks ! it works well
