### ISSUE TITLE
v12.0.0 failed to publish to NPM

### ISSUE THREAD

**Issue by markmssd** [facebook/facebook-nodejs-business-sdk#203]
### Which SDK version are you using?
N/A

### What's the issue?
The Github Actions for publishing `v12.0.0` failed: https://github.com/facebook/facebook-nodejs-business-sdk/actions/runs/1240037741

There seems to be a permission issue with the NPM token.

**Comment by b8ne** [comment]
Is this being fixed? I've just created a new app and it won't let me select v11, so I am stuck on v12 and have no working SDK for it.

**Comment by imBAOSS** [comment]
Same for me! Would appreciate it if this could get addressed please

**Comment by jingping2015** [comment]
Hi, Thanks for reporting this issue. Now v12 is available in npm.
