### ISSUE TITLE
 You are calling a deprecated version of the Ads API. Please update to the latest version: v12.0.", nodejs npm

### ISSUE THREAD

**Issue by siddmegadeth** [facebook/facebook-nodejs-business-sdk#204]
### Which SDK version are you using?
 v12.0.
### What's the issue?
not able to get it work with facebook-nodejs-business-sdk even though the in FB dev the API version are v12.0 by Default

#### Observed Results:
Across all projects

  * What happened?  This could be a description, log output, etc.
  *  You are calling a deprecated version of the Ads API. Please update to the latest version: v12.0.",

#### Expected Results:
should have worked 

  * What did you expect to happen?

**Comment by siddmegadeth** [comment]
finally fixed this issue
for anyone who is using facebook/facebook-nodejs-business-sdk npm and faces this issue 
please perform the following steps

Once npm is installed there is a folder created 

facebook-nodejs-business-sdk /dist

inside this folder you will find multiple .js files like AMD.js,cjs.js,es.js,global.js,life.js,umd.js  etc.....

open each file in an editor
inside the file search for keywork like  VERSION and  SDK_VERSION 
change its values


for example

```

var FacebookAdsApi = function () {
  createClass(FacebookAdsApi, null, [{
    key: 'VERSION',
    get: function get() {
      return 'v11.0';
    }
  }, {
    key: 'SDK_VERSION',
    get: function get() {
      return '11.0.0';
    }
  }, {
    key: 'GRAPH',
    get: function get() {
      return 'https://graph.facebook.com';
    }
  }, {
    key: 'GRAPH_VIDEO',
    get: function get() {
      return 'https://graph-video.facebook.com';
    }

    /**
     * @param {String} accessToken
     * @param {String} [locale]
     */

  }]);

```

would be changed to 

`var FacebookAdsApi = function () {
  createClass(FacebookAdsApi, null, [{
    key: 'VERSION',
    get: function get() {
      return 'v12.0';
    }
  }, {
    key: 'SDK_VERSION',
    get: function get() {
      return '12.0.0';
    }
  }, {
    key: 'GRAPH',
    get: function get() {
      return 'https://graph.facebook.com';
    }
  }, {
    key: 'GRAPH_VIDEO',
    get: function get() {
      return 'https://graph-video.facebook.com';
    }

    /**
     * @param {String} accessToken
     * @param {String} [locale]
     */

  }]);`


restart your nodejs server (do not do npm install again) 

it works like a charm for now

**Comment by liesislukas** [comment]
and you actually closed such issue? So to use official SDK from facebook itself you need to download the sdk, crack it and then use it? Facebook?

**Comment by siddmegadeth** [comment]
> and you actually closed such issue? So to use official SDK from facebook itself you need to download the sdk, crack it and then use it? Facebook?

hello. this is on dev who created it. due to my need i have to dig in and find a solution to it. Fb sdk are a lot confusing

**Comment by liesislukas** [comment]
i was able to resolve this by installing newest SDK and making sure in facebook app newest API is selected. Though fb launched new npm package hours or day after my previous post. 

by apps i mean here: https://developers.facebook.com/apps/

if you use ads API get auth token from ads manager UI event tracking UI and there you need to have fb app too, this app may be special app which just provide tokens for ads APIs, so that APP had old version on it.

This error message should have link to docs or video..
