### ISSUE TITLE
How i can read campaigns of all adAccounts of user?

### ISSUE THREAD

**Issue by DarkScorpion** [facebook/facebook-nodejs-business-sdk#21]
In example wrote how get adAccount campaigns , but not have how get all adAccounts of User.
How get adAccounts of user, and how did batch request for get campaigns ?

**Comment by dolbyzerr** [comment]
For now I am using this workaround:

```js
const me = await api.call('GET', ['me'], {fields: 'adaccounts'})
const {adaccounts: {data: adaccounts}} = me
console.log(adaccounts)
```

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
