### ISSUE TITLE
400 error due to deprecated API endpoint version (fb api is now v15, but this sdk is calling v14)

### ISSUE THREAD

**Issue by cleytoncoro** [facebook/facebook-nodejs-business-sdk#232]
### Which SDK version are you using?
v14

### What's the issue?
FB is now at v15 api. new apps comes with this api by default (and can't be downgraded). When I try to use this sdk, I get the error ""(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v15.0.""

### Steps/Sample code to reproduce the issue
1. Create a new app
2. Use the sdk

#### Observed Results:
400 Error when a request is started.

#### Expected Results:

A success post request.

#### just for reference - workaround:
https://github.com/facebook/facebook-nodejs-business-sdk/issues/224

**Comment by minhphuc010194** [comment]
me too ! 🥲

**Comment by cleytoncoro** [comment]
> I have the same issue, is there any workaround?! 🥲

yes

https://github.com/facebook/facebook-nodejs-business-sdk/issues/224

**Comment by sicsdev** [comment]
You have launched latest version 14. I am using latest 14 version but getting error 
 "error": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v15.0."

**Comment by MrChadMWood** [comment]
@cleytoncoro Is it possible to apply this fix via Python? 

I am unsure if the fix suggests editing the raw code within one of the SDKs files, or if a one-liner can be used after import to apply the fix. It appears that the recommended fix is not for Python too, though please correct me if I am wrong.
