### ISSUE TITLE
version 14 has been deprecated.

### ISSUE THREAD

**Issue by web-planex** [facebook/facebook-nodejs-business-sdk#235]
![image](https://user-images.githubusercontent.com/1082936/196685216-fb6bc023-0c64-4f57-845c-5245e900a3d5.png)

the current version is v15.0

![image](https://user-images.githubusercontent.com/1082936/196685550-e5f62fbc-26b4-402d-8ff5-6353152d4541.png)

{
    "message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v15.0."
}

**Comment by LashaTsatsashvili** [comment]
you can try this temporary solution
```js
const bizSdk = require('facebook-nodejs-business-sdk');
Object.defineProperty(bizSdk.FacebookAdsApi, 'VERSION', { get: () => 'v15.0' });
Object.defineProperty(bizSdk.FacebookAdsApi, 'SDK_VERSION', { get: () => 'v15.0.0' });
```
