### ISSUE TITLE
AdsPixel Id is not defined

### ISSUE THREAD

**Issue by 10xchs** [facebook/facebook-nodejs-business-sdk#259]
> Error: AdsPixel Id not defined
>     at AdsPixel.getId (webpack-internal:///(sc_server)/./node_modules/facebook-nodejs-business-sdk/dist/cjs.js:1321:27)
>     at AdsPixel.getNodePath (webpack-internal:///(sc_server)/./node_modules/facebook-nodejs-business-sdk/dist/cjs.js:1338:29)
>     at AdsPixel.createEdge (webpack-internal:///(sc_server)/./node_modules/facebook-nodejs-business-sdk/dist/cjs.js:1437:26)
>     at AdsPixel.createEvent (webpack-internal:///(sc_server)/./node_modules/facebook-nodejs-business-sdk/dist/cjs.js:25732:29)
>     at EventRequest.execute (webpack-internal:///(sc_server)/./node_modules/facebook-nodejs-business-sdk/dist/cjs.js:28262:68)

Why is everything that Facebook touches so bad?

**Comment by stcheng** [comment]
@10xchs could you provide more context about the error encountered?
