### ISSUE TITLE
17.0.3 introduces error: "TypeError: Cannot read properties of undefined (reading 'map')"

### ISSUE THREAD

**Issue by sgtdck** [facebook/facebook-nodejs-business-sdk#260]
### Which SDK version are you using?

17.0.3

### What's the issue?

When calling endpoints which use `response.data` property, the `buildObjectsFromResponse` method tries to map these data items. However, since 17.0.3, it dies horribly, as it seems the `response` param is now actually `response.data`, thus it tries to perform `response.data.data.map(...)` - and no such property exists. 

It seems that the changes in [this commit](https://github.com/facebook/facebook-nodejs-business-sdk/commit/a2d64d93485f353ad6a3e78709c7d7fc858dcbc2#diff-d45b1674ab37689f6ca6dc634fe29959c463fc30cb46746c3b187de88432ae4fR132) are the culprit.

I have confirmed that downgrading to `17.0.2` fixes the problem immediately.

CC @stcheng as I believe it's your commit

### Steps/Sample code to reproduce the issue

```ts
FacebookAdsApi.init(user.accessToken);
const fbUser = new User(user.userID);
const adAccounts = await fbUser.getAdAccounts(['name']);
console.log('result', adAccounts); // promise will reject, error thrown in console
```

#### Observed Results:

```
"TypeError: Cannot read properties of undefined (reading 'map')
    at Cursor._this._buildObjectsFromResponse (https://localhost:1234/index.7ba870ae.js:70042:34)
    at https://localhost:1234/index.7ba870ae.js:70031:41"
```

  * What happened?  This could be a description, log output, etc.

#### Expected Results:

a neat list of `AdAccount`s

#### Workaround

Use `17.0.2` in the meantime.

**Comment by stcheng** [comment]
checking

**Comment by stcheng** [comment]
@sgtdck I cannot reproduce this issue actually. Internally we have tests covering the cursor and paging scenario. When you did version bump, did you run a clean npm install?

**Comment by stcheng** [comment]
@genlyken could you check if you encountered this issue?

**Comment by genlyken** [comment]
I couldn't reproduce it either. I checked the cjs.js to make sure, and i'm using axios there.

**Comment by sgtdck** [comment]
It appears to have been a (persistent!) glitch in the matrix. After trying to reproduce once more, the bug has vanished.

Sorry for wasting your time, everyone - and thank you for looking into it so prompty. 👍

**Comment by jozsi** [comment]
This is actually happening for every release above 17.0.2 (which is the last usable version in my case).

**Comment by jozsi** [comment]
This is actually happening for every release above 17.0.2 when in a browser environment. Cause it falls back to `xmlHttpRequest`, but a2d64d93485f353ad6a3e78709c7d7fc858dcbc2 has adapted to axios response format, therefore the discrepancy.
