### ISSUE TITLE
TypeError: response.data.map is not a function

### ISSUE THREAD

**Issue by nrjmr432** [facebook/facebook-nodejs-business-sdk#27]
I'm trying to use getReachEstimate with a null fields array and a default set of params, but i'm not getting a proper response.
Response: {"data":{"users":242000000,"estimate_ready":true}}
above is the only response even if i modify the targeting_spec in any way.

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.

**Comment by oggminator** [comment]
Hi, the issue is still in place in v3.2.0 SDK release.

**Comment by codytwinton** [comment]
Ok, good to know. Reopening.

**Comment by jingping2015** [comment]
Would be great you can provide the code you are calling cause this issue.

**Comment by jingping2015** [comment]
I am going to close this since there is no response for long time, feel free to reopen it if this still happen and you can provide us a sample code.
