### ISSUE TITLE
App Events got ineligible for Meta AEM

### ISSUE THREAD

**Issue by bleshik** [facebook/facebook-nodejs-business-sdk#278]
### Which SDK version are you using?
18.0.1

### What's the issue?
All app events that are sent from our backend were working fine, but suddenly got ineligible for Meta AEM. This happened without introducing any changes on the backend on Sunday 17.03.2024. See the screenshot:
<img width="498" alt="Screenshot 2024-03-19 at 10 54 13" src="https://github.com/facebook/facebook-nodejs-business-sdk/assets/1547095/aad5a598-2a0a-43e7-ab2e-cbb5a01e57a2">

### Steps/Sample code to reproduce the issue
Send any event with action source "app" using the nodejs SDK. Then check Events Manager.

#### Observed Results:
As mentioned above, the event got ineligible. Also, we do see the events in Events Manager on the graph:
<img width="1013" alt="Screenshot 2024-03-19 at 10 53 40" src="https://github.com/facebook/facebook-nodejs-business-sdk/assets/1547095/b27b321a-19d2-4851-8660-707f6903b94e">
But nothing in the "Sampled Activities" tab
<img width="973" alt="Screenshot 2024-03-19 at 10 56 49" src="https://github.com/facebook/facebook-nodejs-business-sdk/assets/1547095/9770c5b6-dc39-4ebf-8802-bbec0fa6c2db">

#### Expected Results:
The event to be eligible for Meta AEM as it was working before.

**Comment by bleshik** [comment]
I updated SDK up to the last version around 1 hour ago. We will see if it helps. I guess I should wait for at least 24 hours, right?

**Comment by max-fofanov** [comment]
I have the same problem

**Comment by Grafit24** [comment]
I have the same issue.

**Comment by bleshik** [comment]
Issue got solved after updating iOS sdk to the latest version
