### ISSUE TITLE
Advertisers in Russia cannot create or run ads at this time.

### ISSUE THREAD

**Issue by delgadostech** [facebook/facebook-nodejs-business-sdk#283]
### Which SDK version are you using?
Using latest version v17.0.0

### What's the issue?
Suddenly, all our campaigns and ad sets stopped creating since last Friday, March 29, 2024, throwing this error "Advertisers in Russia cannot create or run ads at this time."
We are based in the US, spend over 1M a year in ads and there's not a single trace of Russian account, ip addresses, pages, anything related to Russia in our business account.

We can manually create campaigns, ad sets and ads using Facebook's Ad Manager Suite.

Downgrading to lower versions of the SDK won't work either.

### Steps/Sample code to reproduce the issue
Just creating a simple campaign triggers the error, creating new ad sets for an existing campaign triggers the error.

#### Observed Results:

  * What happened?  This could be a description, log output, etc.

Here's the error message when trying to create a new campaign:

{"error":{"message":"Invalid parameter","type":"OAuthException","code":100,"error_subcode":3686001,"is_transient":false,"error_user_title":"Ad cannot be published","error_user_msg":"Advertisers in Russia cannot create or run ads at this time.","fbtrace_id":"A2ljUrb-vMVuPk3OAY8dTVZ"}}

#### Expected Results:

  * What did you expect to happen?

We expect that campaigns and ad sets can be created using the API without this issue.

**Comment by stcheng** [comment]
@delgadostech this is not an issue with the SDK or the version of the SDK or API. Could you go to the developers.facebook.com/docs/marketing-apis and submit a support ticket to report this issue? Thank you.
