### ISSUE TITLE
Currency code capitalization?

### ISSUE THREAD

**Issue by seanberto** [facebook/facebook-nodejs-business-sdk#292]
### Which SDK version are you using?

Main branch.

### What's the issue?

In the Main branch, here: https://github.com/facebook/facebook-nodejs-business-sdk/blob/main/src/objects/serverside/utils.js#L123, currency codes are lowercased.

However, in all of Meta's Pixel and CAPI documentation, currency codes are listed as capitalized, following the ISO 4217 specification.

Does Meta Pixel and CAPI accept either capitalized or lowercased versions of Currency codes? What does Meta want to receive for Pixel and CAPI? If it is the capitalized format, why does this Node.js library change currency codes to lower case?

#### Observed Results:

  * As far as I can see, sending currency codes to Meta via Pixel and CAPI isn't impacted by the capitalization of currency codes.

**Comment by stcheng** [comment]
@seanberto it doesn't seem that this will affect the behavior. could you submit a pull request to remove this or change it to toUpperCase to reduce the confusion?

**Comment by seanberto** [comment]
Thanks, @stcheng.

Here's a PR:

https://github.com/facebook/facebook-nodejs-business-sdk/pull/294
