### ISSUE TITLE
Error Message:FacebookRequestError: (#2) Service temporarily unavailable

### ISSUE THREAD

**Issue by scaydogdu** [facebook/facebook-nodejs-business-sdk#31]
An error occurred while processing, Node.js getCampaigns Edge
Error Message:FacebookRequestError: (#2) Service temporarily unavailable
Error Stack:Error

i cant use getCampaigns and similar functions. But i can modify and update them by supplying their id.

**Comment by hanselke** [comment]
getting the same issue trying to getCampaigns.

is this due to a software bug or is the api service not working?

**Comment by vicdus** [comment]
Close. Feel free to reopen if this occurs again.
