### ISSUE TITLE
AdVideo.getThumbnails throws "Error: No endpoint specified for the target edge."

### ISSUE THREAD

**Issue by thierryjacoel** [facebook/facebook-nodejs-business-sdk#35]
The method `getThumbnails` is defined as follow:
``` 
getThumbnails (fields: Object, params: Object): Cursor {
    return this.getEdge(VideoThumbnail, fields, params, 'thumbnails');
  }
```

The call to `getEdge` misses the parameter `fetchFirstPage` in 4th position, thus having the parameter `endpoint` not provided, which ends up in an exception raised when creating the `Cursor`.

Replacing the definition of `getThumbnails` with
```
getThumbnails(fields: Object, params: Object): Cursor {
    var fetchFirstPage = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : true;
    return this.getEdge(adsSdk.VideoThumbnail, fields, params, fetchFirstPage, 'thumbnails');
}
```
fixes the problem.

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.

**Comment by Dai1678** [comment]
I am using the latest version, but this problem has not been resolved in the past.

I think this 1code is necessary for this function.
`var fetchFirstPage = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : true;`

I tried @thierryjacoel suggested code in my local environment and it worked.

@codytwinton  please fixes the problem.

**Comment by codytwinton** [comment]
Thanks for opening #76, but I'm just going to reopen this issue.
