### ISSUE TITLE
Using adsSdk.AdCreativeObjectStorySpec to create an AdCreative returns an error

### ISSUE THREAD

**Issue by thierryjacoel** [facebook/facebook-nodejs-business-sdk#36]
When using an object of type `adsSdk.AdCreativeObjectStorySpec` to assign to the field `object_story_spec` to create a new AdCreative, Facebook returns an error stating:
```
object_story_spec param is invalid
Object story spec is ill formed. Maybe missing Page ID or creative details, or invalid fields exist
```
Replacing the ObjectStorySpec instantiation by a simple JavaScript object `{}` fixes the problem.

**Comment by michaelwclark** [comment]
AdCreativeObjectStorySpec is a function that creates a class. If you are trying to set object_story_spec param in AdCreative it's expecting params  similiar to the below. note that the right side are just variable names, you'd need to fill in your data appropriatly or not use that line.

```
const object_story_spec = {
   [adsSdk.AdCreativeObjectStorySpec.instagram_actor_id]: instagram_actor_id,
   [adsSdk.AdCreativeObjectStorySpec.link_data]: link_data,
   [adsSdk.AdCreativeObjectStorySpec.photo_data]: photo_data,
   [adsSdk.AdCreativeObjectStorySpec.template_data] : template_data,
   [adsSdk.AdCreativeObjectStorySpec.text_data]: text_data,
   [adsSdk.AdCreativeObjectStorySpec.video_data]: video_data
}

```

**Comment by thierryjacoel** [comment]
So that class only exists for the `Fields` lookup ? It's not supposed to be used as a value to pass in to an `AdCreative`, nor to be expected in the field `adCreative.object_story_spec` ?

**Comment by michaelwclark** [comment]
Yea for now all that class does is expose the valid fields.

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
