### ISSUE TITLE
Creating several objects with the same AdAccount instance returns an error

### ISSUE THREAD

**Issue by thierryjacoel** [facebook/facebook-nodejs-business-sdk#39]
When trying to create several objects, for example a campaign and an adset using the same instance of `AdAccount`, eg:
```
const account = new AdAccount(ACCOUNT_ID);

account.createCampaign(...)
.then(campaign => {
    account.createAdSet(...)
})
```
Facebook returns an error `Unsupported post request. Object with ID '.....' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api` for the second create call

The problem disapears if I replace this with:
```
new AdAccount(ACCOUNT_ID).createCampaign(...)
.then(campaign => {
    new AdAccount(ACCOUNT_ID).createAdSet(...)
})
```

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
