### ISSUE TITLE
Effective status filter fails

### ISSUE THREAD

**Issue by trip1** [facebook/facebook-nodejs-business-sdk#41]
I'm attempting to fetch all ads that are currently active, accoring to the Ads Manager page, that should be about 130 ads. Yet when this is ran I'm easily getting over 300 (I killed the server at that point). I'm getting ads that have been completed or ended months and sometimes years ago. Not sure if my query is setup incorrectly or if I'm confusing how the effective status is set for the ads. All I need is just the list of current ads that are being delivered.

This is what I'm using to get all the ads:

```javascript
const ad_fields = [
  Ad.Fields.name,
  Ad.Fields.id,
  Ad.Fields.effective_status,
  Ad.Fields.created_time,
  Ad.Fields.updated_time,
  Ad.Fields.status
];
const ad_filters = {
  [Ad.Fields.effective_status]: [Ad.ConfiguredStatus.active],
}

account
.getAds(ad_fields, ad_filters)
.then(handle_res)
.catch(err => console.error(err));
```

Anyone had this issue before or have any advice?

**Comment by ellentao** [comment]
Hi,

Thanks for your comment! It looks like it's related to API parameter setup. Could you report this on developer site https://developers.facebook.com/support/bugs/? Basically, we handle SDK issues in github threads, and handle API issues on developer site. Thank you!
