### ISSUE TITLE
Error message is undefined

### ISSUE THREAD

**Issue by thierryjacoel** [facebook/facebook-nodejs-business-sdk#42]
I have tried to create a new AdAccount for my business, and I can see in the network panel of the browser devtools that I get an error with a message `One or more of the ad accounts in your business manager are currently in bad standing or in review.  All of your accounts must be in good standing in order to create or add new ad accounts.`

However, when I try to display the error message to the user, the message is `undefined`.

I can see when I console log the `FacebookRequestError` that the `message` field is indeed `undefined`. When looking at the source, it seems that the generation of the Error object expects a `name` property on the object returned by Facebook, but it is not present (maybe a legacy thing).

Adding a general case in https://github.com/facebook/facebook-nodejs-ads-sdk/blob/master/src/exceptions.js#L68 would at least allow a non-conventional value for the `name` to not ignore the message returned.

**Comment by codytwinton** [comment]
It seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.

**Comment by NovoManu** [comment]
Hi,
Error is still happens.
![1](https://user-images.githubusercontent.com/22621380/44308235-35ffc800-a3ba-11e8-9601-300d8c6ef493.jpg)
![2](https://user-images.githubusercontent.com/22621380/44308237-3b5d1280-a3ba-11e8-8604-01e358c67628.jpg)

**Comment by codytwinton** [comment]
Ok, thanks for the heads up!

**Comment by NovoManu** [comment]
Didn't fixed yet

**Comment by bduffany** [comment]
Still not fixed :/

**Comment by bduffany** [comment]
Did some digging. The `FacebookRequestError` class [here](https://github.com/facebook/facebook-nodejs-business-sdk/blob/0b31c7746ef36b55d83fcb9f937b8a3bb571c8b3/src/exceptions.js#L34) is expecting an object that looks like an error returned by the `requestPromise` API. But in the browser, `XMLHttpRequest` is used, not `requestPromise`. The structure of the error object is completely different (see the code [here](https://github.com/facebook/facebook-nodejs-business-sdk/blob/720290931e20ab9f73758d195d1fac814f242836/src/http.js#L58)).

**Comment by bduffany** [comment]
Any update on this? It makes the API very difficult to use on the client side, since we can't properly log errors.

**Comment by bduffany** [comment]
Hi, the issue is still present and my PR is still open. https://github.com/facebook/facebook-nodejs-business-sdk/pull/158
