### ISSUE TITLE
Pass in access token during create/update call

### ISSUE THREAD

**Issue by jkpchang** [facebook/facebook-nodejs-business-sdk#43]
Hi,

I am working on a system where there are multiple users with different access tokens to create campaigns. How do I pass in access token during Campaign.create() call as oppose to sdk.init(access_token) which is global? otherwise, I am going to run into race condition.

**Comment by michaelwclark** [comment]
you can pass in an optional params object in the 2nd param of your create. 
```

account
  .createCampaign(
    [],
  {
    [Campaign.Fields.name]: 'Test Campaign - Delete',
    [Campaign.Fields.status]: Campaign.Status.paused,
    [Campaign.Fields.objective]: Campaign.Objective.page_likes,
     token: 'xxxx',
     other_param:'xxxxx'
  }
  )
  .then(console.log)
  .catch(console.error);

```

**Comment by ellentao** [comment]
Thanks @michaelwclark for answering this question!
