### ISSUE TITLE
How can I create a campaign as an A / B test?

### ISSUE THREAD

**Issue by mur71mur** [facebook/facebook-nodejs-business-sdk#46]
I have made adStudy.
but It is not reflected in the advertisement manager.

To create a campaign as an A / B test, create a campaign with iterative_split_test_configs ?
please tell me iterative_split_test_configs's sample.

Or update a campaign with adStudy's id ??

**Comment by ellentao** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
