### ISSUE TITLE
How would you add users to custom audience?

### ISSUE THREAD

**Issue by trip1** [facebook/facebook-nodejs-business-sdk#47]
I've created custom audiences based off some of the examples, but I don't see anywhere that says how to add the users to the custom audience. I've tried looking through the other SDK's and it looks they each have a specific function that adds the users to it. I tried using the `custom-audience-data-source` object to put the hashes in but still no luck. Also tried just placing the schema type and data source in the fields and params when calling the function but neither seem to do anything either. Can it be done with the SDK or do I just have to use something else?

**Comment by michaelwclark** [comment]
It's the same flow as the initial create. Just POST to the <CUSTOM_AUDIENCE_ID>/users endpoint.  It's the same as your initial population of the custom audience to add more users. Here is an example CURL request to do so.

```
curl \
  -F 'payload={ 
    "schema": "EMAIL_SHA256", 
    "data": [ 
      "9b431636bd164765d63c573c346708846af4f68fe3701a77a3bdd7e7e5166254", 
      "8cc62c145cd0c6dc444168eaeb1b61b351f9b1809a579cc9b4c9e9d7213a39ee", 
      "4eaf70b1f7a797962b9d2a533f122c8039012b31e0a52b34a426729319cb792a" 
    ] 
  }' \
  -F 'access_token=<ACCESS_TOKEN>' \
  https://graph.facebook.com/v2.11/<CUSTOM_AUDIENCE_ID>/users
```

**Comment by laziob** [comment]
As trip1 said, I've tried those ways too and still no luck. When passing the payload as an object inside params, it returns a 400 error stating that the payload object is missing

**Comment by laziob** [comment]
I did one more try, and cant tell yet if it is working properly but at least got a 200 response.

The params where like this:
  const params = {
    "payload" : "\
    {'schema' : 'EMAIL_SHA256',\
    'data' : ['9b431636bd164765d63c573c346708846af4f68fe3701a77a3bdd7e7e5166254', '8cc62c145cd0c6dc444168eaeb1b61b351f9b1809a579cc9b4c9e9d7213a39ee', '4eaf70b1f7a797962b9d2a533f122c8039012b31e0a52b34a426729319cb792a']\
    }"};

Hope it helps!
