### ISSUE TITLE
package.json dependancies seem off and bloated.

### ISSUE THREAD

**Issue by michaelwclark** [facebook/facebook-nodejs-business-sdk#52]
# package.json
[here](https://github.com/facebook/facebook-nodejs-business-sdk/blob/master/package.json#L57,L68)
    "mixwith": "~0.1.1",
    "request": "^2.81.0",
    "request-promise": "~4.1.1", 
Are the only deps that make sense to me here. Not sure why all the others made it in. They should be in dev dependancies. Unneeded bloat for everyone who uses your package.

**Comment by mledom** [comment]
Agreed, we just ran npm install and noticed phantomJS building downloaded. Its being included from glow-flowtype. I agree with @michaelwclark seems like there are a lot of deps that should be moved to devDep.

**Comment by bertero** [comment]
##__Update:__
I manually removed the `phantom`, `phantomjs-prebuilt` and `unicode-5.2.0` modules and then normally retrieved and updated campaigns and adSets data.

Something doesn't seem right here guys...

**Comment by yassera2** [comment]
I'm facing the same issue. Specifically, we're using AWS lambda and the node modules are exceeding the package size limit because of those extra dependencies.

**Comment by mledom** [comment]
I'm in the same boat as @yassera2, I'm having trouble deploying to AWS Lambda. I was able to remove the two that @bertero mentioned (thanks!) Seems like there is some optimization that could take place.

**Comment by michaelwclark** [comment]
I'm going to do a PR hopefully today with the fix. Also in the likely and common event that it takes 6+ weeks to I'll do a fork of this. I don't want to do that, but at this point the whole community is struggling with this issue and we need to keep it moving forward.

**Comment by michaelwclark** [comment]
@mledom @denimlabs/facebook-nodejs-business-sdk is our active fork. I've been releasing a few times a week so far. Feel free to use that. It reduced our build signifigantly. The PR was approved to reduce size, but idk the release schedule with these guys maybe @codytwinton can shed some light on that?

**Comment by codytwinton** [comment]
We have merged #73 internally and it should be available on the next release.
