### ISSUE TITLE
Insights API

### ISSUE THREAD

**Issue by himanshuj89** [facebook/facebook-nodejs-business-sdk#63]
Hi - 

I am having trouble getting data using Insights API. Below is the piece of code I have - 

const adsSdk = require('facebook-nodejs-business-sdk');

const accessToken = "XXXXX";

const account = new AdAccount('act_XXXXXX');

account.getInsights([AdInsight.Fields.impressions,AdInsight.Fields.spend,AdInsight.Fields.cpc, AdInsight.Fields.cpm], {
    level: AdInsight.Level.adset
})
.then((insights) => {

  console.log(insights.length) // returns 0

})
.catch((error) => {
	console.log(error)
});

It always returns 0 insights; i have tried couple of combinations. Am i doing something wrong here?

thanks.

**Comment by felixk42** [comment]
Have you tried this on the Graph API explorer ?

**Comment by hojun920** [comment]
may be, insights is not array. 

try it -> console.log(insights)

**Comment by Flintlozk** [comment]
first args in getInsights func 
try to input a field like 
- ['impressions','spend','cpc',cpm']
and then a level parameter only accepts 
'enum {ad, adset, campaign, account}'
