### ISSUE TITLE
Concurrency and sdk mutation

### ISSUE THREAD

**Issue by distrill** [facebook/facebook-nodejs-business-sdk#64]
We have a bunch of jobs that we would like to run concurrently. However, if we do so we have no guarantee that the appropriate token will be used. Simple reproduction case follows:

``` javascript
const adsSdk = require('facebook-nodejs-business-sdk');
const Promise = require('bluebird');

const { AdAccount } = adsSdk;

async function runForAccount(actId, token, waitTime) {
  adsSdk.FacebookAdsApi.init(token);

  console.log('waiting for', waitTime, 'ms (', token, ')');
  await Promise.delay(waitTime);
  const account = new AdAccount(actId);

  try {
    const info = await account.read([AdAccount.Fields.name, AdAccount.Fields.age]);
    console.log(info._data);
  } catch (err) {
    console.log('bad token failed');
  }
}

const actId = '<act_id>';
const badToken = '<bad_token>';
const goodToken = '<good_token>';

runForAccount(actId, goodToken, 2000);
runForAccount(actId, badToken, 10);

```

desired output:
``` shell
bad token failed
{ id: '<id>', name: '<name>', age: '<age>' }
```

actual output
```
bad token failed
bad token failed
```

Is there some way to work around this so that we can have multiple instances of the sdk running at the same time? Or is there a plan to support this kind of use in the future? Javascript in particular is heavily asynchronous, this side-effect behavior is not desirable. We've resorted to making the requests directly ourselves for now but would prefer to use the official sdk if possible.

**Comment by JoakimLandberg** [comment]
Looks like you'll have to explicitly create an instance of FacebookAdsApi and use that as a constructor argument, rather than relying on the default instance created by the static ```init``` method.

```
const api = new FacebookAdsApi(token)

const account = new AdAccount(actId, {}, null, api);
```

**Comment by c990802** [comment]
I would like to suggest, for the good of the sdk and the developers using it, to better document this method for instantiating the API.

I'm sure that a common use case of this sdk is for developers who create apps who have multiple clients. Therefore, for each client needs a different `user_token`. In the README, only mentions the instantiation method to set up a global `user_token` for all the API calls.

It's easy to omit this detail and detail jump into other areas of code. In our case, the code was similar to the example provided & it never failed until we run it concurrently with different consumers who required different user tokens. During development, you don't have concurrency and this error can be easily leaked. Idem with tests.

Thanks.
