### ISSUE TITLE
Bug in FacebookAdsApiBatch callbacks

### ISSUE THREAD

**Issue by paraboom** [facebook/facebook-nodejs-business-sdk#67]
Hello, guys, I started to use your library and found a pretty nasty bug in `FacebookAdsApiBatch`.
In the constructor we could pass `successCallback` as a parameter, so it'll be saved in the pool of callbacks:
```
constructor (
    api: FacebookAdsApi,
    successCallback?: Function,
    failureCallback?: Function
  ) {

    ...

    if (successCallback != null) {
      this._successCallbacks.push(successCallback);
    }

    if (failureCallback != null) {
      this._failureCallbacks.push(failureCallback);
    }
  }
```

When we're adding requests to the batch, we could pass `successCallback` as well, but during execution callbacks applied from the common pool of callbacks (including general success callback, which we passed in constructor):
```
for (let index = 0; index < responses.length; index++) {
  const response = responses[index];

  if (response != null) {
    const apiResponse = new APIResponse(response, this._batch[index]);

    // Call the success callback if provided
    if (apiResponse.isSuccess) {
      if (this._successCallbacks[index]) {
        this._successCallbacks[index](apiResponse);
      }
    } else {
      // Call the failure callback if provided
      if (this._failureCallbacks[index]) {
        this._failureCallbacks[index](apiResponse);
      }
    }
  } else {
    // Do not get response, so, we keep track of the index to retry
    retryIndices.push(index);
  }
}
```

So here `index` is an index of response, but when we add general success callback, amount of callbacks will be always `response.length + 1`, so last success callback will never be called.

And it seems the same situation with `failureCallbacks`.

**Comment by michaelwclark** [comment]
Good catch. I'll take a crack at fixing this soon. I'd like to clean up this section of code anyways.

**Comment by paraboom** [comment]
It seems all related code was refactored and there's no error anymore. Thanks!
