### ISSUE TITLE
fields on the ads-insights object in this sdk are not available in the marketing api

### ISSUE THREAD

**Issue by distrill** [facebook/facebook-nodejs-business-sdk#68]
We started getting errors last night for asking for the following fields:
```
[ 'total_actions',
  'total_unique_actions',
  'social_clicks',
  'social_reach',
  'unique_social_clicks',
  'call_to_action_clicks',
  'cost_per_total_action' ]
```

To use `social_clicks` as an example, here it is as a field in the source for this repo https://github.com/facebook/facebook-nodejs-business-sdk/blob/master/src/objects/ads-insights.js#L66 and here are the docs for the same version that I'm checking against https://developers.facebook.com/docs/marketing-api/reference/ads-insights/v3.0. `social_clicks` is not listed in the official docs.

What's particularly weird is that this code has been deployed for some time without issue, we just started seeing this error last night.

**Comment by marcinlerka** [comment]
I'm facing the same problem. Yesterday some metrics were deprecated by Facebook. Check out this breaking changes info: https://developers.facebook.com/docs/graph-api/changelog/breaking-changes#feb2018

**Comment by michaelwclark** [comment]
Yea this is expected. They should be removed from AdInsights.Fields. I'll do a PR.
