### ISSUE TITLE
Urgent: Facebook version deprication v2.12

### ISSUE THREAD

**Issue by biznickman** [facebook/facebook-nodejs-business-sdk#70]
I'm using this library yet for some reason Facebook's developer interface states:

```
Your app [App Name], currently accesses a version of the Marketing API prior to v2.12. We will be deprecating all versions prior to v2.12 on Tuesday, August 7, 2018. 
```

**Comment by yoann-trouillet** [comment]
I am not getting this error : { error:
{ message: '(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v3.0.' } }

when can we expect a new release ?

**Comment by tom-james-watson** [comment]
From reading the source, it looks like they've renamed and republished the package (thanks for the heads up 😑) to `facebook-nodejs-business-sdk`. Installing that instead of `facebook-nodejs-ads-sdk` should give you a version that uses v3.0.

**Comment by codytwinton** [comment]
@tom-james-watson - Thanks for commenting this.

@biznickman - Changing to call the new `facebook-nodejs-business-sdk` should indeed solve your issue.
