### ISSUE TITLE
Unable to create a campaign

### ISSUE THREAD

**Issue by Greathyx** [facebook/facebook-nodejs-business-sdk#71]
every time I try to create a campaign, I receive the same error:
{
   "error": {
      "message": "Unsupported get request. Object with ID '2114859988835111' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api",
      "type": "GraphMethodException",
      "code": 100,
      "error_subcode": 33,
      "fbtrace_id": "BSlaX0BrTDt"
   }
}

**Comment by SandiaSolutions** [comment]
Don't post your ID on github btw, but try to ad "act_"+youre_id when instantiating a new  AdAccount. However I have noticed that the Ads API being used here is 2.11, which is deprecated
