### ISSUE TITLE
confused about how to use the sdk

### ISSUE THREAD

**Issue by flyfj** [facebook/facebook-nodejs-business-sdk#74]
I installed the sdk via npm. When I'm creating the api object, it gives me errors about can't resolve packages, e.g. aws-sign2 etc. Then I go into the sdk itself under node_modules/ and run `npm install`, the errors still exist.

What is supposed to be the correct way to use the sdk?

**Comment by michaelwclark** [comment]
`aws-sign2` isn't in this package at all. Likely your package.json  or system npm/node is not properly configured. If you share your package.json and the exact error that might help us debug.
