### ISSUE TITLE
[REOPEN] AdVideo.getThumbnails throws "Error: No endpoint specified for the target edge." #35

### ISSUE THREAD

**Issue by Dai1678** [facebook/facebook-nodejs-business-sdk#76]
This problem has not been resolved in the past in the v3.0.0.

This bug is in ad-video.js, getThumbnails()

I think this 1code is necessary for this function.
`var fetchFirstPage = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : true;`

Here is the past issue ↓
https://github.com/facebook/facebook-nodejs-business-sdk/issues/35

**Comment by codytwinton** [comment]
Will address in #35
