### ISSUE TITLE
How to upload the video to Asset library in  using video url and this SDK ?

### ISSUE THREAD

**Issue by Dai1678** [facebook/facebook-nodejs-business-sdk#77]
I want to upload the video to Asset library using video url.
video url is like this format.
`https://scontent.xx.fbcdn.net/~`

I use the Graph Explorer for already uploaded videos, this url was in "source".

I was able to find several classes about video (video-uploader.js, ad-account.js, ad-video.js), but I do not know how to write the code.

Would you tell me the sample code?

**Comment by Dai1678** [comment]
Also, I want to get video_id after uploading video.

**Comment by mvhirsch** [comment]
@Dai1678 there is an example on how to do this on https://developers.facebook.com/docs/marketing-api/advideo/v4.0#create

Hope this helps :-)
