### ISSUE TITLE
Deleting Ad Studies

### ISSUE THREAD

**Issue by CarlousF** [facebook/facebook-nodejs-business-sdk#79]
Hi there,

I couldn't seem to find a function for deleting Ad Studies, either in the business object or the ad-study object, so I'm having to circumvent the SDK when deleting Ad Studies, and call the API directly.

Would it be possible to get support for deleting Ad Studies via the SDK in a future release?

Thanks,

Carlous

**Comment by michaelwclark** [comment]
I've opened a PR #81  for this. I will also merge this into my forked master tonight. I'll be trying to keep up with maintenance of issues in our companies version as we rely heavily on this SDK. I have written several similar tools, but seeing facebook do their own we decided to lean on their stuff. Unfortunatly this is a small team that maintains the SDK, so we are trying to pickup the slack and hopefully helpout the community.

`npm i @denimlabs/facebook-nodejs-business-sdk`
https://github.com/denimlabs/facebook-nodejs-business-sdk/

version 3.1.3 includes the deleteAdStudy method on AdStudy object.

**Comment by CarlousF** [comment]
@michaelwclark Thanks, just checked this out and it worked for me, and successfully deleted the Ad Study!

Could we rename the function from `deleteAdStudy` to `delete` to be more in keeping with the deletion functions used for other objects (e.g. Ads, Ad Sets etc)?

**Comment by michaelwclark** [comment]
Fixed in  @denimlabs/facebook-nodejs-business-sdk version 3.2.1

**Comment by codytwinton** [comment]
@michaelwclark - Thanks for all the work on maintaining your fork!

**Comment by michaelwclark** [comment]
@codytwinton you're very welcome. We use this heavily at our work, so it's important to keep this project active for us.  If possible to become a maintainer, despite not being @fb.com, on this main repo I'd love to do that. If not though, no worries. I can impliment fun features in my fork that you might not otherwise.

**Comment by jingping2015** [comment]
Close it since the issue has been solved.
