### ISSUE TITLE
Urgent: Facebook version deprication. Need to use v3.1

### ISSUE THREAD

**Issue by StanHilliar** [facebook/facebook-nodejs-business-sdk#85]
I am using the "facebook-nodejs-business-sdk" packages and attempting to create a new custom audience through the examples: "(AdAccount(id)).createCustomAudience"
But I'm getting this error:
status: 400,                                                                                                                                             response: { 
    error:  { 
        message: '(#2635) You are calling a deprecated version of the Ads API. Please update to the latest 
        version: v3.1.',                                      
        type: 'OAuthException',                                                                                                                                  
        code: 2635,                                                                                                                                              
        fbtrace_id: 'GnFNl+uJQTf' } },                                                                                                                     
   method: 'POST',                                                                                                                                          
   url: 'https://graph.facebook.com/v3.0/........

Updating the api.js and cjs.js files to 3.1 solves this issue however I cannot rely on this for my final solution which would not allow me access into modifying these files.
If you could please update this to the latest Facebook API version 3.1 so that I can use this package properly for future dev

**Comment by jingping2015** [comment]
Did you update to our latest package? I think now we are v3.1

**Comment by StanHilliar** [comment]
@jingping2015 I have updated it again now and it seems to be on v3.1. Thank you
