### ISSUE TITLE
Unable to share line of credit between Parent BM and Child BM

### ISSUE THREAD

**Issue by sparxHub** [facebook/facebook-nodejs-business-sdk#88]
We are trying to onboard our customer but we get an error "(#3) App must be on whitelist" (code: 3) when calling _**createOwningCreditAllocationConfig**_ after generate a Child Business Manager. 

Running with all the relevant permission as specified on documents. (business_management, ads_read, ads_management) 

```javascript
bizSdk.FacebookAdsApi.init(partner_<ACCESS_TOKEN>_for_smb_onboarding);
fields = [
];

params = {
  'receiving_business_id' : child_business_id,
  'amount' : '10',
};

let extended_credit = await (new ExtendedCredit(<EXTENDED_CREDIT_LINE_ID>)).createOwningCreditAllocationConfig(
  fields,
  params
);
```

Maybe someone knows what is wrong? Thanks :)

**Comment by jingping2015** [comment]
Hi thanks for reporting this issue.
Looks like your app not allowed to make this call. If you are a Facebook Marketing Partner, please reach out to your representative for further assistance. If not, please see the following site on how to become a Facebook Marketing Partner (https://www.facebook.com/business/marketing-partners/about/facebook-marketing-partner-requirements).
