### ISSUE TITLE
AdAccounts Edge demo not working

### ISSUE THREAD

**Issue by Xeoncross** [facebook/facebook-nodejs-business-sdk#89]
The following demo fails: https://github.com/facebook/facebook-nodejs-business-sdk/blob/master/examples/user_ad_accounts_edge.js

    (new User(id)).getAdAccounts()

> message: '(#100) Tried accessing nonexisting field (adaccounts) on node type (AdAccount)

An alternative way to get this data is using the Graph API endpoint:

    fb.api('/me/adaccounts', {access_token: accessToken}).then(...);

**Comment by Xeoncross** [comment]
Solved, I was mistakenly using an account id instead of a user id. Apparently the system detects the `act_XXXXXX` prefix on the ID and returns a `AdAccount` instance instead of a user instance.

**Comment by jingping2015** [comment]
For the id, I think you should use a userID instead of an adaccountID
