### ISSUE TITLE
HTTP Status 400 on preflight wont throw error.

### ISSUE THREAD

**Issue by perengb** [facebook/facebook-nodejs-business-sdk#91]
In src/http.js the request object lacks a onerror eventlistener, if the access_token of the user expires there is no way to see if the http request failed because of this

PR: https://github.com/facebook/facebook-nodejs-business-sdk/pull/90

**Comment by michaelwclark** [comment]
Great work. Hoping to see this implimented soon. Is this mission critical for you? If so feel free to PR into [our fork](https://github.com/denimlabs/facebook-nodejs-business-sdk/) and i'll release this very soon.
