### ISSUE TITLE
Why are there no tests for this library? 

### ISSUE THREAD

**Issue by dwjohnston** [facebook/facebook-nodejs-business-sdk#92]
I'm looking for examples of how others have done tests, [specifically to see how people have managed to do mocking/spying of module functions](https://stackoverflow.com/questions/53736766/what-is-the-state-of-the-art-for-testing-mocking-functions-within-a-module-in-20) - and specifically API handling tests - I'm surprised that there are no tests here.

**Comment by jingping2015** [comment]
Hi,
If you are looks for example about how to use this nodejs SDK, you can check https://github.com/facebook/facebook-nodejs-business-sdk/tree/master/examples

We're a small team, and it doesn't look as though anyone in the community is actively working on this issue in short term, so we've decided to close it. If you plan to send us a pull request resolving the issue let us know.
