### ISSUE TITLE
When I call get getInsights I get the following error Its working earlier but when I updated node_modules by deleting package.lock.json I am getting this error.

### ISSUE THREAD

**Issue by andygit89** [facebook/facebook-nodejs-business-sdk#93]
FacebookRequestError: Syntax error "Expected end of string instead of "s"." at character 658: account_currency,actions,canvas_avg_view_percent,canvas_avg_view_time,clicks,cost_per_10_sec_video_view,cost_per_action_type,cost_per_estimated_ad_recallers,cost_per_inline_link_click,cost_per_inline_post_engagement,cost_per_outbound_click,cost_per_unique_action_type,cost_per_unique_click,cost_per_unique_inline_link_click,cost_per_unique_outbound_click,cpc,cpm,cpp,ctr,date_start,date_stop,estimated_ad_recall_rate,estimated_ad_recallers,frequency,impressions,inline_link_click_ctr,inline_link_clicks,inline_post_engagement,mobile_app_purchase_roas,outbound_clicks,outbound_clicks_ctr,place_page_name,reach,relevance_score,social_spend,spend,,unique_actions,unique_clicks,unique_ctr,unique_inline_link_click_ctr,unique_inline_link_clicks,unique_link_clicks_ctr,unique_outbound_clicks,unique_outbound_clicks_ctr,video_10_sec_watched_actions,video_30_sec_watched_actions,video_avg_percent_watched_actions,video_avg_time_watched_actions,video_p100_watched_actions,video_p25_watched_actions,video_p50_watched_actions,video_p75_watched_actions,video_p95_watched_actions,website_ctr,website_purchase_roas

**Comment by jingping2015** [comment]
Hi, Thanks for your feedback, it will be great you can put you sample code here and also provide which version are you using.

**Comment by andygit89** [comment]
@jingping2015 This is sample of code
      const insightParams = { date_preset: 'lifetime' };
      const adsetInsights = await adSet.getInsights([
        AdsInsights.Fields.account_currency,
        AdsInsights.Fields.actions,
        AdsInsights.Fields.canvas_avg_view_percent,
        AdsInsights.Fields.canvas_avg_view_time,
        AdsInsights.Fields.clicks,
        AdsInsights.Fields.cost_per_10_sec_video_view,
        AdsInsights.Fields.cost_per_action_type,
        AdsInsights.Fields.cost_per_estimated_ad_recallers,
        AdsInsights.Fields.cost_per_inline_link_click,
        AdsInsights.Fields.cost_per_inline_post_engagement,
        AdsInsights.Fields.cost_per_outbound_click,
        AdsInsights.Fields.cost_per_unique_action_type,
        AdsInsights.Fields.cost_per_unique_click,
        AdsInsights.Fields.cost_per_unique_inline_link_click,
        AdsInsights.Fields.cost_per_unique_outbound_click,
        AdsInsights.Fields.cpc,
        AdsInsights.Fields.cpm,
        AdsInsights.Fields.cpp,
        AdsInsights.Fields.ctr,
        AdsInsights.Fields.date_start,
        AdsInsights.Fields.date_stop,
        AdsInsights.Fields.estimated_ad_recall_rate,
        AdsInsights.Fields.estimated_ad_recallers,
        AdsInsights.Fields.frequency,
        AdsInsights.Fields.impressions,
        AdsInsights.Fields.inline_link_click_ctr,
        AdsInsights.Fields.inline_link_clicks,
        AdsInsights.Fields.inline_post_engagement,
        AdsInsights.Fields.mobile_app_purchase_roas,
        AdsInsights.Fields.outbound_clicks,
        AdsInsights.Fields.outbound_clicks_ctr,
        AdsInsights.Fields.place_page_name,
        AdsInsights.Fields.reach,
        AdsInsights.Fields.relevance_score,
        AdsInsights.Fields.social_spend,
        AdsInsights.Fields.spend,
        AdsInsights.Fields.total_action_value,
        AdsInsights.Fields.unique_actions,
        AdsInsights.Fields.unique_clicks,
        AdsInsights.Fields.unique_ctr,
        AdsInsights.Fields.unique_inline_link_click_ctr,
        AdsInsights.Fields.unique_inline_link_clicks,
        AdsInsights.Fields.unique_link_clicks_ctr,
        AdsInsights.Fields.unique_outbound_clicks,
        AdsInsights.Fields.unique_outbound_clicks_ctr,
        AdsInsights.Fields.video_10_sec_watched_actions,
        AdsInsights.Fields.video_30_sec_watched_actions,
        AdsInsights.Fields.video_avg_percent_watched_actions,
        AdsInsights.Fields.video_avg_time_watched_actions,
        AdsInsights.Fields.video_p100_watched_actions,
        AdsInsights.Fields.video_p25_watched_actions,
        AdsInsights.Fields.video_p50_watched_actions,
        AdsInsights.Fields.video_p75_watched_actions,
        AdsInsights.Fields.video_p95_watched_actions,
        AdsInsights.Fields.website_ctr,
        AdsInsights.Fields.website_purchase_roas,
      ], insightParams);

I think this issue is coming with version 3.2.4 by the way in package.json I define "^3.0.1" but in package.lock.json it using the latest vesion 3.2.4

**Comment by andygit89** [comment]
I debug more this error  started coming from version 3.2.0.It's working fine with earlier version.
