### ISSUE TITLE
Flow complains about ad_account_ad_creatives_post_create_carousel_call_to_action_app_install

### ISSUE THREAD

**Issue by dannyjlaurence-exp** [facebook/facebook-nodejs-business-sdk#94]
Hey, we use this package with flow, and after the commit 15 days ago (https://github.com/facebook/facebook-nodejs-business-sdk/commit/e2b82da614e099a8bddfcb3a052ee73725e3ad5b), flow is complaining on compilation about the following file
```
examples/ad_account_ad_creatives_post_create_carousel_call_to_action_app_install.js, line 37. 
```

Looks like a quote snuck into the JSON (look at the value for description): 
```javascript
... 'name':'The link name','description':'The link's description',' ...
```
And flow is (correctly) saying that there is invalid syntax.

**Comment by jingping2015** [comment]
Fixed in new release.
