### ISSUE TITLE
(#4) Application request limit reached"

### ISSUE THREAD

**Issue by carlosbbraga** [facebook/facebook-nodejs-business-sdk#97]
I´m doing a small application to work with leads, however after a few ( ok, a lot ) of bulking tests, I´m getting this error.

Does anyone know exactly facebook´s application request limit? 

PS: My app is still on development mode!

{
  "error": {
    "message": "(#4) Application request limit reached",
    "type": "OAuthException",
    "is_transient": true,
    "code": 4,
    "fbtrace_id": "FlQgl+5U8pF"
  }
}

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
