### ISSUE TITLE
Invalid Fields on AdInsights

### ISSUE THREAD

**Issue by michaelwclark** [facebook/facebook-nodejs-business-sdk#98]
This [commit](https://github.com/facebook/facebook-nodejs-business-sdk/commit/897a8aad7f87046707e2ce50c5935d7de0091543) introduced fields on [AdsInsights](https://github.com/facebook/facebook-nodejs-business-sdk/blob/master/src/objects/ads-insights.js)  that are not valid. 

When calling 

```
    const remoteFields = Object.values(AdsInsights.Fields)
    const facebookCampaign = new Campaign(id)
    const remoteParams = { ...rest, level: 'campaign', date_preset: 'lifetime' }
    const result =  await facebookCampaign.getInsights(remoteFields, remoteParams)
```

Facebook API will generate an Error:

```
 { message:
         '(#100) activity_recency, ad_format_asset, age, bid_type, body_asset, call_to_action_asset, country, creative_fingerprint, description_asset, device_platform, dma, frequency_value, gender, hourly_stats_aggregated_by_advertiser_time_zone, hourly_stats_aggregated_by_audience_time_zone, image_asset, impression_device, link_url_asset, media_asset, place_page_id, placement, platform_position, product_format, product_id, publisher_platform, purchasing_interface, region, rule_asset, title_asset, video_asset, id are not valid for fields param. please check https://developers.facebook.com/docs/marketing-api/reference/ads-insights/ for all valid values',
        type: 'OAuthException',
        code: 100,
        fbtrace_id: 'BePqjg4PDZk' }
```

These fields are invalid in Marketing API v3.2 for AdsInsights:

```
activity_recency
ad_format_asset
age
bid_type
body_asset
call_to_action_asset
country
creative_fingerprint
description_asset
device_platform
dma
frequency_value
gender
hourly_stats_aggregated_by_advertiser_time_zone
hourly_stats_aggregated_by_audience_time_zone
image_asset
impression_device
link_url_asset
media_asset
place_page_id
placement
platform_position
product_format
product_id
publisher_platform
purchasing_interface
region
rule_asset
title_asset
video_asset
```

To resolve the above fields should be removed. 

Shall I PR?

**Comment by michaelwclark** [comment]
I may have spoken too soon. It appears that some of these are valid on insights breakdowns, but not on all insights calls on all objects. If this is the case I believe the SDK should have each breakdown insights object defined expliclty for ease of use. One of the reasons I began using the SDK was to ease the pain of upkeep with the Facebook APIs (and even more specifically this exact object). By utilizing `Object.keys(AdsInsights.Fields)` as my parameter to send to the API  I can usually safely get every field needed from the API, until now I was without worry regarding invalid fields. I would very much be in favor of this change, and if requested would even spearhead this change myself and PR. 

Any thoughts from the maintainers?

**Comment by jingping2015** [comment]
Hi, Thanks for reporting this. Since `AdsInsight` used in different use case and some of these fields only be available for certain case, so please list all the fields you want and don't use `Object.values(AdsInsights.Fields)`.
This is a very special case for `AdsInsight` and since we're a small team, and it doesn't look as though anyone in the community is actively working on this issue now. We will put it into our long-term issue list but we may not be able to fix this in short-term, so I will close this issue now.
