### ISSUE TITLE
How to filter for dates using leads api

### ISSUE THREAD

**Issue by carlosbbraga** [facebook/facebook-nodejs-business-sdk#99]
I know this is no issue, but I am out of resources to look for.

Facebook´s documentation is terrible and I have tested all the possibilities I could find/think of.

I want to filter my Leads by date: Example /2169370176435902/leads?limit=25&until=1543060800

Somewhere I´ve found that the filter for dates used are "since" and "until" and the date values should be UNIX, but it doesn´t seem to work doesn´t matter what I input there.

**Comment by jingping2015** [comment]
Hi, we are not expert of each API, you can ask in our community https://www.facebook.com/groups/pmdcommunity/ or search our docs https://developers.facebook.com/docs/marketing-apis/

**Comment by carlosbbraga** [comment]
> Hi, we are not expert of each API, you can ask in our community https://www.facebook.com/groups/pmdcommunity/ or search our docs https://developers.facebook.com/docs/marketing-apis/

You´ve build the sdk and you don´t know the features of the api ?? That is a little scary.
But that´s fine, I´ve built my own solution already

**Comment by jlubeck** [comment]
hey @carlosbbraga what solution did you find? Can you share it please?

Thank you
